apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app
        image: sandeepyerra/streamlit-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501

---

apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
spec:
  selector:
    app: streamlit-app
  type: NodePort  # Changed from LoadBalancer to NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      # NodePort field is optional; Kubernetes will auto-assign a port if omitted
      # nodePort: 30007  # Uncomment and set this if you want to specify the NodePort

